server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: SpringAPIGateway

  cloud:
    gateway:
      routes:
      - id: Search
        uri: http://localhost:8091
        predicates:
        - Path=/search/**
      - id: Booking
        uri: http://localhost:8092
        predicates:
        - Path=/booking/**
      - id: CheckIn
        uri: http://localhost:8093
        predicates:
        - Path=/checkin/**
      - id: Payment
        uri: http://localhost:8094
        predicates:
        - Path=/payment/**
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"